# Generated by Django 4.1.3 on 2023-04-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
